name: CMake Build Matrix

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: sudo apt-get install -y --no-install-recommends gcc-8 g++-8
    - name: Build
      run: |
          mkdir build
          cd build
          CC=gcc-8 CXX=g++-8 cmake ..
          make VERBOSE=1

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ninja
      run: choco install ninja
    - name: Build
      run: |
          cmake -GNinja .
          ninja

