name: CMake Build Matrix

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: sudo apt-get install -y --no-install-recommends gcc-8 g++-8
    - name: Build
      env:
        CC: gcc-8
        CXX: g++-8
      run: |
          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        CC: cl
        CXX: cl
      shell: powershell
      run: |
          . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -G "NMake Makefiles" .
          nmake

